sudo : required

services:
  - docker

before_install:
  - docker build -t xueszrd/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true -t xueszrd/react-test npm test -- --coverage

after_success:
  - docker build -t xueszrd/complex-client ./client
  - docker build -t xueszrd/complex-nginx ./nginx
  - docker build -t xueszrd/complex-server ./server
  - docker build -t xueszrd/complex-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin 

  - docker push xueszrd/complex-client
  - docker push xueszrd/complex-nginx
  - docker push xueszrd/complex-server
  - docker push xueszrd/complex-worker